### ISSUE TITLE
Any advice on compiling this project?

### ISSUE THREAD

**Issue by sweetbbak** [FigBug/bfxr#1]
I wanted to try out bfxr alternatives after learning that it was made in Adobe air... I tried running
```sh
g++ *.cpp -o bfxr
```
with no luck. Do you have any advice on how I could compile this?

**Comment by FigBug** [comment]
This is just the audio engine from bfxr, there is no UI or anything. It needs to be built into an app to do anything. I use it in a plugin called SFX8 https://github.com/FigBug/slPlugins/tree/master/plugins/SFX8

To build that, there is a build script in the ci folder

**Comment by sweetbbak** [comment]
Thank you!
